### ISSUE TITLE
[nima-test] Overrides Scope HttpClient

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-nima#12]
It seems the HttpClient configured by the test plugin totally overrides any HttpClient created in the beanScope. Can we make this only injected into the test?

**Comment by rob-bygrave** [comment]
> test plugin totally overrides any HttpClient created in the beanScope

Sort of.

When running tests there are multiple BeanScopes in a hierarchy.  

- "_Global_" test scope (bottom) ... which has the Application BeanScope + overridden dependencies from `@TestScope`
- _Test static scope_ (per test class with "global" as the parent)
- _Test instance scope_ (per test instance with the "test static" or global as parent)

So the BeanScope coming in is not the "Global" scope but either the Test static scope or the Test instance scope.

So its "shadowing/override" and not "replacement" going on here.


> overrides

Where I see an issue is that we currently lose the configuration of the HttpClient like a global ErrorHandler.

What I think might solve that issue is a method like a `httpClient clone() / builder() / prototype()` method that returns a new HttpClient.Builder with all the configuration that was set on the original HttpClient instance (like global error handlers etc) ... and then the base url is overridden on that.


What was the original issue / source of this question?

**Comment by SentryMan** [comment]
I'm rewriting one of my services, and have a test where we start the entire application but point our HTTP client in the service layer to local embedded wiremock endpoints to test. 

I'm trying to use this feature to call the application controller, but it seems that the HTTP client in my service layer has been overridden and thus fails to call the mock endpoints.

**Comment by SentryMan** [comment]
hmm, actually wait a sec the issue might be with the test

**Comment by SentryMan** [comment]
ah woops like it was my imagination
